[package]
name = "tu"
description = "TimeUP!"
version = "0.1.0"
authors = ["Julio Biason <julio.biason@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.11"
clap = "2.33.0"
serde = "*"
serde_derive = "*"
toml = "0.5"
